[platformio]
src_dir = ROBOT_AI/src
include_dir = ROBOT_AI/include
lib_dir = ROBOT_AI/lib
test_dir = ROBOT_AI/test

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = send_on_enter
upload_port = COM*
monitor_port = COM*
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17
    -O2
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -I$PROJECT_DIR/ROBOT_AI/include
    -I$PROJECT_DIR/ROBOT_AI/src
    -I$PROJECT_DIR/ROBOT_AI/lib/Core
    -I$PROJECT_DIR/ROBOT_AI/lib/Interfaces
    -I$PROJECT_DIR/ROBOT_AI/lib/Control
    -I$PROJECT_DIR/ROBOT_AI/lib/Encoder
    -I$PROJECT_DIR/ROBOT_AI/lib/ROS2Protocol
    -I$PROJECT_DIR/ROBOT_AI/lib/Sensor_HC_SR04
    -I$PROJECT_DIR/ROBOT_AI/lib/Motor
    -I$PROJECT_DIR/ROBOT_AI/lib/Mpu6050
    -I$PROJECT_DIR/ROBOT_AI/lib/BLEManager
lib_ldf_mode = deep+
lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    BTS7960
    MH_FMD
    Motor
    Mpu6050
    ROS2Protocol
    Sensor_HC_SR04
    Encoder
    h2zero/NimBLE-Arduino @ ^1.4.2
